@startuml
skinparam classAttributeIconSize 0

class AssignOwnerTask {
      -User user
      -Chain nextInChain
      +setNextChain(Chain nextChain):void
      +assignTask(User user) :void
      +getUser(): User
      +setUser(User user):void
}

class AssignCEOTask {
      -User user
      -Chain nextInChain
      +setNextChain(Chain nextChain):void
      +assignTask(User user) :void
      +getUser(): User
      +setUser(User user):void
}

class AssignManagerTask {
      -User user
      -Chain nextInChain
      +setNextChain(Chain nextChain):void
      +assignTask(User user) :void
      +getUser(): User
      +setUser(User user):void
}

class AssignEmployeeTask {
      -User user
      -Chain nextInChain
      +setNextChain(Chain nextChain):void
      +assignTask(User user) :void
      +getUser(): User
      +setUser(User user):void
}

class TaskAssignmentDriver {
    +main():void
}

interface Chain {
    +setNextChain(Chain nextChain):void
    +assignTask(User user):void
}

 Chain  <|-- AssignOwnerTask
 Chain  <|-- AssignCEOTask
 Chain  <|-- AssignManagerTask
 Chain  <|-- AssignEmployeeTask
 TaskAssignmentDriver --> Chain

@enduml